apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}-config
  namespace: default
data:
  sha: "{{ .Values.commit.sha }}"
  branch: "{{ .Values.commit.branch }}"
  repo: "{{ .Values.commit.repo }}"
